name: transformer_pytorch

channels:
  - pytorch
  - conda-forge
  - apple # Including apple channel for M1 compatibility
  - defaults

dependencies:
  - python=3.11.4
  - jupyter
  - numpy
  - scikit-learn
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - black
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - pip:
      - openai
      - python-dotenv
      - langchain
      - docarray
      - tiktoken
      - chromadb
      - transformers
      - datasets
      - tensorboard

# For M1 Macs, use PyTorch's special build
platforms:
  - osx-arm64
